Conversion from tileKey into extendedSpatialID
trajectoryjp/spatial_id_go pull request #27
Opened 2024-08-01 00:28 UTC by mi-24v

## feature

- tileKey->extendedSpatialId conversion via `ConvertQuadkeysAndAltitudekeysToExtendedSpatialIDs`
- documentation for `ConvertQuadkeysAndAltitudekeysToExtendedSpatialIDs`

2024-08-02 09:05 UTC, HarutakaMatsumoto requested changes
I reviewed it.
Check it out.

2024-08-02 09:05 UTC, HarutakaMatsumoto commented on transform/convert_quadkey_and_Vertical_id_test.go
Why do you change all of this?

2024-08-02 10:10 UTC, mi-24v commented on transform/convert_quadkey_and_Vertical_id_test.go
It seems to be CRLF -> LF conversion was made in [e5825d39](https://github.com/trajectoryjp/spatial_id_go/commit/e5825d39f233b801210b63e999f4a3d1b1dfcc53?diff=split&w=1)
using `ignore whitespace` will  suppress too many diff
need fix?

2024-08-16 10:42 UTC, mi-24v commented
it founds that QuadkeysAndAltitudekeys should not be used in new feature (#28 )
This PR will be closed and replacement Pull Request is to considered.

2024-08-16 10:42 UTC, closed without merging