Using radixtree for check spatialIDs' overlap
trajectoryjp/spatial_id_go pull request #35
Opened 2024-10-11 11:49 UTC by mi-24v

2024-10-16 09:06 UTC, HarutakaMatsumoto requested changes
I reviewed this.
Check it out.

2024-10-17 05:42 UTC, mi-24v commented on test/detect_overlap/main.go
> +func main() {
moved at [d1587dd](https://github.com/trajectoryjp/spatial_id_go/pull/35/commits/d1587dd2528c7f5feb363c4ed47689c61b998f94) and [e6054cc](https://github.com/trajectoryjp/spatial_id_go/pull/35/commits/e6054ccc06ea26cc8f98b05b6c44befc53c1fd92)

2024-10-17 05:43 UTC, mi-24v commented on transform/convert_quadkey_and_Vertical_id.go
> +// したがって ConvertZToAltitudekey(f, z, z, consts.ZBaseExponent, zBaseOffset)と等価
changed at [056776c](https://github.com/trajectoryjp/spatial_id_go/pull/35/commits/056776c4a44c233e34b83ca4fb0b0a52e472801d)

And `AddZBaseOffsetToZ` was removed at [a0e7440](https://github.com/trajectoryjp/spatial_id_go/pull/35/commits/a0e744016df071d6e4b05c6e5ade5dcc47a9f70c)

2024-10-18 04:37 UTC, merged

2024-10-18 04:40 UTC, HarutakaMatsumoto commented
@mi-24v 
I merged it.
Thank you for your contribution!